### ISSUE TITLE
About Multi-modal RLHF

### ISSUE THREAD

**Issue by junkunyuan** [opendilab/awesome-RLHF#26]
Hi, I wonder if there is a multi-modal dataset for RLHF training of multi-modal large language models.

**Comment by PaParaZz1** [comment]
Maybe you can keep track of this [repo](https://github.com/opendilab/awesome-multi-modal-reinforcement-learning).

> Hi, I wonder if there is a multi-modal dataset for RLHF training of multi-modal large language models.

**Comment by junkunyuan** [comment]
> Maybe you can keep track of this [repo](https://github.com/opendilab/awesome-multi-modal-reinforcement-learning).
> 
> > Hi, I wonder if there is a multi-modal dataset for RLHF training of multi-modal large language models.

Thanks very much!
